
language: node_js
node_js:
  - "stable"

install: 
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database storemanagertest;' -U postgres
  - psql -c 'CREATE USER User WITH PASSWORD 'ebenezer';' -U postgres
env:
  - NODE_ENV=test

test:
  - npm test

after_success:
  - npm run coveralls